services:
  postgres:
    container_name: postgres
    image: postgres:16.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: UTC
      PGTZ: UTC
    volumes: 
      - postgres:/var/lib/postgresql/data
      # copy the sql script to create schema and tables
      - ./postgres/sql/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
    networks:
      - default
  
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: fabiano
      MONGO_INITDB_ROOT_PASSWORD: fabiano
    volumes:
      - ./mongodb/db_data/:/data/db/      
    networks:
       - default

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.6    
    restart: always
    ports:
      - "8080:8080"    
    command:
      start-dev  
    environment:  
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_USER: fabiano
      DB_PASSWORD: fabiano
    volumes:
      - keycloak:/data
      - ./keycloak/providers:/opt/jboss/keycloak/providers
      - ./keycloak/standalone/configuration:/opt/jboss/keycloak/standalone/configuration
    depends_on:
      - postgres       

volumes:
  postgres:
    driver: local
  mongodb:
    driver: local
  keycloak:
    driver: local  